const { DogPics } = require('../models');

const DogsPicData = [
    {APIname:"akita", commonName: "Akita", dogPic: "https://images.dog.ceo/breeds/akita/An_Akita_Inu_resting.jpg"},
{APIname:"akita", commonName: "Akita", dogPic: "https://images.dog.ceo/breeds/akita/Japaneseakita.jpg"},
{APIname:"appenzeller", commonName: "Appenzeller", dogPic: "https://images.dog.ceo/breeds/appenzeller/n02107908_2340.jpg"},
{APIname:"appenzeller", commonName: "Appenzeller", dogPic: "https://images.dog.ceo/breeds/appenzeller/n02107908_3926.jpg"},
{APIname:"australian/shepherd", commonName: "Australian Shepherd", dogPic: "https://images.dog.ceo/breeds/australian-shepherd/forest.jpg"},
{APIname:"australian/shepherd", commonName: "Australian Shepherd", dogPic: "https://images.dog.ceo/breeds/australian-shepherd/sadie.jpg"},
{APIname:"basenji", commonName: "Basenji", dogPic: "https://images.dog.ceo/breeds/basenji/n02110806_581.jpg"},
{APIname:"basenji", commonName: "Basenji", dogPic: "https://images.dog.ceo/breeds/basenji/n02110806_849.jpg"},
{APIname:"beagle", commonName: "Beagle", dogPic: "https://images.dog.ceo/breeds/beagle/n02088364_11147.jpg"},
{APIname:"beagle", commonName: "Beagle", dogPic: "https://images.dog.ceo/breeds/beagle/n02088364_852.jpg"},
{APIname:"coonhound", commonName: "Bluetick Coonhound", dogPic: "https://images.dog.ceo/breeds/coonhound/n02089078_3078.jpg"},
{APIname:"coonhound", commonName: "Bluetick Coonhound", dogPic: "https://images.dog.ceo/breeds/coonhound/n02089078_482.jpg"},
{APIname:"boxer", commonName: "Boxer", dogPic: "https://images.dog.ceo/breeds/boxer/n02108089_2482.jpg"},
{APIname:"boxer", commonName: "Boxer", dogPic: "https://images.dog.ceo/breeds/boxer/n02108089_6008.jpg"},
{APIname:"bulldog/english", commonName: "English Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg"},
{APIname:"bulldog/english", commonName: "English Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-english/mami.jpg"},
{APIname:"bulldog/french", commonName: "French Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-french/n02108915_5596.jpg"},
{APIname:"bulldog/french", commonName: "French Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-french/n02108915_618.jpg"},
{APIname:"cattledog/australian", commonName: "Australian Cattledog", dogPic: "https://images.dog.ceo/breeds/cattledog-australian/IMG_1042.jpg"},
{APIname:"cattledog/australian", commonName: "Australian Cattledog", dogPic: "https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg"},
{APIname:"chihuahua", commonName: "Chihuahua", dogPic: "https://images.dog.ceo/breeds/chihuahua/n02085620_2517.jpg"},
{APIname:"chihuahua", commonName: "Chihuahua", dogPic: "https://images.dog.ceo/breeds/chihuahua/n02085620_275.jpg"},
{APIname:"chow", commonName: "Chow Chow", dogPic: "https://images.dog.ceo/breeds/chow/n02112137_16388.jpg"},
{APIname:"chow", commonName: "Chow Chow", dogPic: "https://images.dog.ceo/breeds/chow/n02112137_16665.jpg"},
{APIname:"collie/border", commonName: "Border Collie", dogPic: "https://images.dog.ceo/breeds/collie-border/n02106166_7804.jpg"},
{APIname:"collie/border", commonName: "Border Collie", dogPic: "https://images.dog.ceo/breeds/collie-border/niuniu.jpg"},
{APIname:"corgi/cardigan", commonName: "Corgi", dogPic: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11220.jpg"},
{APIname:"corgi/cardigan", commonName: "Corgi", dogPic: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_13484.jpg"},
{APIname:"dachshund", commonName: "Dachshund", dogPic: "https://images.dog.ceo/breeds/dachshund/daschund-1.jpg"},
{APIname:"dachshund", commonName: "Dachshund", dogPic: "https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg"},
{APIname:"dalmatian", commonName: "Dalmatian", dogPic: "https://images.dog.ceo/breeds/dalmatian/cooper1.jpg"},
{APIname:"dalmatian", commonName: "Dalmatian", dogPic: "https://images.dog.ceo/breeds/dalmatian/cooper2.jpg"},
{APIname:"dane/great", commonName: "Great Dane", dogPic: "https://images.dog.ceo/breeds/dane-great/n02109047_1005.jpg"},
{APIname:"dane/great", commonName: "Great Dane", dogPic: "https://images.dog.ceo/breeds/dane-great/n02109047_1284.jpg"},
{APIname:"doberman", commonName: "Doberman", dogPic: "https://images.dog.ceo/breeds/doberman/n02107142_10070.jpg"},
{APIname:"doberman", commonName: "Doberman", dogPic: "https://images.dog.ceo/breeds/doberman/n02107142_9621.jpg"},
{APIname:"germanshepherd", commonName: "German Shepherd", dogPic: "https://images.dog.ceo/breeds/germanshepherd/n02106662_13368.jpg"},
{APIname:"germanshepherd", commonName: "German Shepherd", dogPic: "https://images.dog.ceo/breeds/germanshepherd/n02106662_2631.jpg"},
{APIname:"greyhound/italian", commonName: "Italian Greyhound", dogPic: "https://images.dog.ceo/breeds/greyhound-italian/n02091032_652.jpg"},
{APIname:"greyhound/italian", commonName: "Italian Greyhound", dogPic: "https://images.dog.ceo/breeds/greyhound-italian/n02091032_9018.jpg"},
{APIname:"hound/afghan", commonName: "Afghan Hound", dogPic: "https://images.dog.ceo/breeds/hound-afghan/n02088094_10822.jpg"},
{APIname:"hound/afghan", commonName: "Afghan Hound", dogPic: "https://images.dog.ceo/breeds/hound-afghan/n02088094_1370.jpg"},
{APIname:"hound/blood", commonName: "Blood Hound", dogPic: "https://images.dog.ceo/breeds/hound-blood/n02088466_6834.jpg"},
{APIname:"hound/blood", commonName: "Blood Hound", dogPic: "https://images.dog.ceo/breeds/hound-blood/n02088466_7046.jpg"},
{APIname:"husky", commonName: "Husky", dogPic: "https://images.dog.ceo/breeds/husky/n02110185_3589.jpg"},
{APIname:"husky", commonName: "Husky", dogPic: "https://images.dog.ceo/breeds/husky/n02110185_6105.jpg"},
{APIname:"kelpie", commonName: "Kelpie", dogPic: "https://images.dog.ceo/breeds/kelpie/n02105412_1530.jpg"},
{APIname:"kelpie", commonName: "Kelpie", dogPic: "https://images.dog.ceo/breeds/kelpie/n02105412_5702.jpg"},
{APIname:"labradoodle", commonName: "Labradoodle", dogPic: "https://images.dog.ceo/breeds/labradoodle/Cali.jpg"},
{APIname:"labradoodle", commonName: "Labradoodle", dogPic: "https://images.dog.ceo/breeds/labradoodle/labradoodle-forrest.jpg"},
{APIname:"labrador", commonName: "Labrador Retriver", dogPic: "https://images.dog.ceo/breeds/labrador/Luke.jpg"},
{APIname:"labrador", commonName: "Labrador Retriver", dogPic: "https://images.dog.ceo/breeds/labrador/n02099712_7866.jpg"},
{APIname:"maltese", commonName: "Maltese", dogPic: "https://images.dog.ceo/breeds/maltese/n02085936_5582.jpg"},
{APIname:"maltese", commonName: "Maltese", dogPic: "https://images.dog.ceo/breeds/maltese/n02085936_9812.jpg"},
{APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/2.jpg"},
{APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/2.jpg"},
{APIname:"mix", commonName: "Mix", dogPic: "https://images.dog.ceo/breeds/mix/luna.jpg"},
{APIname:"mix", commonName: "Mix", dogPic: "https://images.dog.ceo/breeds/mix/Polo.jpg"},
{APIname:"mountain/bernese", commonName: "Bernese Mountain", dogPic: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_3908.jpg"},
{APIname:"mountain/bernese", commonName: "Bernese Mountain", dogPic: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_4061.jpg"},
{APIname:"newfoundland", commonName: "Newfoundland", dogPic: "https://images.dog.ceo/breeds/newfoundland/n02111277_3653.jpg"},
{APIname:"newfoundland", commonName: "Newfoundland", dogPic: "https://images.dog.ceo/breeds/newfoundland/n02111277_7225.jpg"},
{APIname:"pinscher/miniature", commonName: "Miniature Pinscher", dogPic: "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_3823.jpg"},
{APIname:"pinscher/miniature", commonName: "Miniature Pinscher", dogPic: "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_957.jpg"},
{APIname:"pitbull", commonName: "Pitbull", dogPic: "https://images.dog.ceo/breeds/pitbull/20190710_143021.jpg"},
{APIname:"pitbull", commonName: "Pitbull", dogPic: "https://images.dog.ceo/breeds/pitbull/20190801_154956.jpg"},
{APIname:"pointer/german", commonName: "German Pointer", dogPic: "https://images.dog.ceo/breeds/pointer-german/n02100236_2974.jpg"},
{APIname:"pointer/german", commonName: "German Pointer", dogPic: "https://images.dog.ceo/breeds/pointer-german/n02100236_5141.jpg"},
{APIname:"pomeranian", commonName: "Pomeranian", dogPic: "https://images.dog.ceo/breeds/pomeranian/n02112018_6149.jpg"},
{APIname:"pomeranian", commonName: "Pomeranian", dogPic: "https://images.dog.ceo/breeds/pomeranian/n02112018_725.jpg"},
{APIname:"poodle/toy", commonName: "Toy Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-toy/n02113624_2308.jpg"},
{APIname:"poodle/toy", commonName: "Toy Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-toy/n02113624_3624.jpg"},
{APIname:"poodle/standard", commonName: "Standard Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-standard/n02113799_153.jpg"},
{APIname:"poodle/standard", commonName: "Standard Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-standard/n02113799_2466.jpg"},
{APIname:"pug", commonName: "Pug", dogPic: "https://images.dog.ceo/breeds/pug/n02110958_11306.jpg"},
{APIname:"pug", commonName: "Pug", dogPic: "https://images.dog.ceo/breeds/pug/n02110958_16082.jpg"},
{APIname:"retriever/golden", commonName: "Golden Retriever", dogPic: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3494.jpg"},
{APIname:"retriever/golden", commonName: "Golden Retriever", dogPic: "https://images.dog.ceo/breeds/retriever-golden/PXL_20220424_121025943.MP.jpg"},
{APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/3.jpg"},
{APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/4.jpg"},
{APIname:"samoyed", commonName: "Samoyed", dogPic: "https://images.dog.ceo/breeds/samoyed/n02111889_3960.jpg"},
{APIname:"samoyed", commonName: "Samoyed", dogPic: "https://images.dog.ceo/breeds/samoyed/ruby.jpg"},
{APIname:"setter/english", commonName: "English Setter", dogPic: "https://images.dog.ceo/breeds/setter-english/n02100735_4172.jpg"},
{APIname:"setter/english", commonName: "English Setter", dogPic: "https://images.dog.ceo/breeds/setter-english/n02100735_6658.jpg"},
{APIname:"setter/irish", commonName: "Irish Setter", dogPic: "https://images.dog.ceo/breeds/setter-irish/n02100877_5925.jpg"},
{APIname:"setter/irish", commonName: "Irish Setter", dogPic: "https://images.dog.ceo/breeds/setter-irish/n02100877_8595.jpg"},
{APIname:"sheepdog/english", commonName: "English Sheepdog", dogPic: "https://images.dog.ceo/breeds/sheepdog-english/n02105641_12610.jpg"},
{APIname:"sheepdog/english", commonName: "English Sheepdog", dogPic: "https://images.dog.ceo/breeds/sheepdog-english/n02105641_4796.jpg"},
{APIname:"shiba", commonName: "Shiba Inu", dogPic: "https://images.dog.ceo/breeds/shiba/kurosuke01.jpg"},
{APIname:"shiba", commonName: "Shiba Inu", dogPic: "https://images.dog.ceo/breeds/shiba/shiba-1.jpg"},
{APIname:"spaniel/cocker", commonName: "Cocker Spaniel", dogPic: "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_11443.jpg"},
{APIname:"spaniel/cocker", commonName: "Cocker Spaniel", dogPic: "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_4782.jpg"},
{APIname:"springer/english", commonName: "English Springer", dogPic: "https://images.dog.ceo/breeds/springer-english/n02102040_5604.jpg"},
{APIname:"springer/english", commonName: "English Springer", dogPic: "https://images.dog.ceo/breeds/springer-english/n02102040_735.jpg"},
{APIname:"terrier/american", commonName: "American Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-american/n02093428_111.jpg"},
{APIname:"terrier/american", commonName: "American Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-american/n02093428_2049.jpg"},
{APIname:"terrier/scottish", commonName: "Scotish Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-scottish/n02097298_8452.jpg"},
{APIname:"terrier/scottish", commonName: "Scotish Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-scottish/n02097298_9499.jpg"},
{APIname:"terrier/yorkshire", commonName: "Yorkshire Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2748.jpg"},
{APIname:"terrier/yorkshire", commonName: "Yorkshire Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3704.jpg"},
{APIname:"weimaraner", commonName: "Weimaraner", dogPic: "https://images.dog.ceo/breeds/weimaraner/n02092339_1331.jpg"},
{APIname:"weimaraner", commonName: "Weimaraner", dogPic: "https://images.dog.ceo/breeds/weimaraner/n02092339_452.jpg"},
{APIname:"whippet", commonName: "Whippet", dogPic: "https://images.dog.ceo/breeds/whippet/n02091134_15398.jpg"},
{APIname:"whippet", commonName: "Whippet", dogPic: "https://images.dog.ceo/breeds/whippet/n02091134_3522.jpg"},
{APIname:"wolfhound/irish", commonName: "Irish Wolfhound", dogPic: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_272.jpg"},
{APIname:"wolfhound/irish", commonName: "Irish Wolfhound", dogPic: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_4006.jpg"}
]

const seedDogPics = () => DogPics.bulkCreate(DogsPicData);

module.exports = seedDogPics;
