const { DogPics } = require('../models');

const DogsPicData = [
{id:"1", APIname:"akita", commonName: "Akita", dogPic: "https://images.dog.ceo/breeds/akita/An_Akita_Inu_resting.jpg"},
{id:"2", APIname:"akita", commonName: "Akita", dogPic: "https://images.dog.ceo/breeds/akita/Japaneseakita.jpg"},
{id:"3", APIname:"appenzeller", commonName: "Appenzeller", dogPic: "https://images.dog.ceo/breeds/appenzeller/n02107908_2340.jpg"},
{id:"4", APIname:"appenzeller", commonName: "Appenzeller", dogPic: "https://images.dog.ceo/breeds/appenzeller/n02107908_3926.jpg"},
{id:"5", APIname:"australian/shepherd", commonName: "Australian Shepherd", dogPic: "https://images.dog.ceo/breeds/australian-shepherd/forest.jpg"},
{id:"6", APIname:"australian/shepherd", commonName: "Australian Shepherd", dogPic: "https://images.dog.ceo/breeds/australian-shepherd/sadie.jpg"},
{id:"7", APIname:"basenji", commonName: "Basenji", dogPic: "https://images.dog.ceo/breeds/basenji/n02110806_581.jpg"},
{id:"8", APIname:"basenji", commonName: "Basenji", dogPic: "https://images.dog.ceo/breeds/basenji/n02110806_849.jpg"},
{id:"9", APIname:"beagle", commonName: "Beagle", dogPic: "https://images.dog.ceo/breeds/beagle/n02088364_11147.jpg"},
{id:"10", APIname:"beagle", commonName: "Beagle", dogPic: "https://images.dog.ceo/breeds/beagle/n02088364_852.jpg"},
{id:"11", APIname:"coonhound", commonName: "Bluetick Coonhound", dogPic: "https://images.dog.ceo/breeds/coonhound/n02089078_3078.jpg"},
{id:"12", APIname:"coonhound", commonName: "Bluetick Coonhound", dogPic: "https://images.dog.ceo/breeds/coonhound/n02089078_482.jpg"},
{id:"13", APIname:"boxer", commonName: "Boxer", dogPic: "https://images.dog.ceo/breeds/boxer/n02108089_2482.jpg"},
{id:"14", APIname:"boxer", commonName: "Boxer", dogPic: "https://images.dog.ceo/breeds/boxer/n02108089_6008.jpg"},
{id:"15", APIname:"bulldog/english", commonName: "English Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg"},
{id:"16", APIname:"bulldog/english", commonName: "English Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-english/mami.jpg"},
{id:"17", APIname:"bulldog/french", commonName: "French Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-french/n02108915_5596.jpg"},
{id:"18", APIname:"bulldog/french", commonName: "French Bulldog", dogPic: "https://images.dog.ceo/breeds/bulldog-french/n02108915_618.jpg"},
{id:"19", APIname:"cattledog/australian", commonName: "Australian Cattledog", dogPic: "https://images.dog.ceo/breeds/cattledog-australian/IMG_1042.jpg"},
{id:"20", APIname:"cattledog/australian", commonName: "Australian Cattledog", dogPic: "https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg"},
{id:"21", APIname:"chihuahua", commonName: "Chihuahua", dogPic: "https://images.dog.ceo/breeds/chihuahua/n02085620_2517.jpg"},
{id:"22", APIname:"chihuahua", commonName: "Chihuahua", dogPic: "https://images.dog.ceo/breeds/chihuahua/n02085620_275.jpg"},
{id:"23", APIname:"chow", commonName: "Chow Chow", dogPic: "https://images.dog.ceo/breeds/chow/n02112137_16388.jpg"},
{id:"24", APIname:"chow", commonName: "Chow Chow", dogPic: "https://images.dog.ceo/breeds/chow/n02112137_16665.jpg"},
{id:"25", APIname:"collie/border", commonName: "Border Collie", dogPic: "https://images.dog.ceo/breeds/collie-border/n02106166_7804.jpg"},
{id:"26", APIname:"collie/border", commonName: "Border Collie", dogPic: "https://images.dog.ceo/breeds/collie-border/niuniu.jpg"},
{id:"27", APIname:"corgi/cardigan", commonName: "Corgi", dogPic: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11220.jpg"},
{id:"28", APIname:"corgi/cardigan", commonName: "Corgi", dogPic: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_13484.jpg"},
{id:"29", APIname:"dachshund", commonName: "Dachshund", dogPic: "https://images.dog.ceo/breeds/dachshund/daschund-1.jpg"},
{id:"30", APIname:"dachshund", commonName: "Dachshund", dogPic: "https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg"},
{id:"31", APIname:"dalmatian", commonName: "Dalmatian", dogPic: "https://images.dog.ceo/breeds/dalmatian/cooper1.jpg"},
{id:"32", APIname:"dalmatian", commonName: "Dalmatian", dogPic: "https://images.dog.ceo/breeds/dalmatian/cooper2.jpg"},
{id:"33", APIname:"dane/great", commonName: "Great Dane", dogPic: "https://images.dog.ceo/breeds/dane-great/n02109047_1005.jpg"},
{id:"34", APIname:"dane/great", commonName: "Great Dane", dogPic: "https://images.dog.ceo/breeds/dane-great/n02109047_1284.jpg"},
{id:"35", APIname:"doberman", commonName: "Doberman", dogPic: "https://images.dog.ceo/breeds/doberman/n02107142_10070.jpg"},
{id:"36", APIname:"doberman", commonName: "Doberman", dogPic: "https://images.dog.ceo/breeds/doberman/n02107142_9621.jpg"},
{id:"37", APIname:"germanshepherd", commonName: "German Shepherd", dogPic: "https://images.dog.ceo/breeds/germanshepherd/n02106662_13368.jpg"},
{id:"38", APIname:"germanshepherd", commonName: "German Shepherd", dogPic: "https://images.dog.ceo/breeds/germanshepherd/n02106662_2631.jpg"},
{id:"39", APIname:"greyhound/italian", commonName: "Italian Greyhound", dogPic: "https://images.dog.ceo/breeds/greyhound-italian/n02091032_652.jpg"},
{id:"40", APIname:"greyhound/italian", commonName: "Italian Greyhound", dogPic: "https://images.dog.ceo/breeds/greyhound-italian/n02091032_9018.jpg"},
{id:"41", APIname:"hound/afghan", commonName: "Afghan Hound", dogPic: "https://images.dog.ceo/breeds/hound-afghan/n02088094_10822.jpg"},
{id:"42", APIname:"hound/afghan", commonName: "Afghan Hound", dogPic: "https://images.dog.ceo/breeds/hound-afghan/n02088094_1370.jpg"},
{id:"43", APIname:"hound/blood", commonName: "Blood Hound", dogPic: "https://images.dog.ceo/breeds/hound-blood/n02088466_6834.jpg"},
{id:"44", APIname:"hound/blood", commonName: "Blood Hound", dogPic: "https://images.dog.ceo/breeds/hound-blood/n02088466_7046.jpg"},
{id:"45", APIname:"husky", commonName: "Husky", dogPic: "https://images.dog.ceo/breeds/husky/n02110185_3589.jpg"},
{id:"46", APIname:"husky", commonName: "Husky", dogPic: "https://images.dog.ceo/breeds/husky/n02110185_6105.jpg"},
{id:"47", APIname:"kelpie", commonName: "Kelpie", dogPic: "https://images.dog.ceo/breeds/kelpie/n02105412_1530.jpg"},
{id:"48", APIname:"kelpie", commonName: "Kelpie", dogPic: "https://images.dog.ceo/breeds/kelpie/n02105412_5702.jpg"},
{id:"49", APIname:"labradoodle", commonName: "Labradoodle", dogPic: "https://images.dog.ceo/breeds/labradoodle/Cali.jpg"},
{id:"50", APIname:"labradoodle", commonName: "Labradoodle", dogPic: "https://images.dog.ceo/breeds/labradoodle/labradoodle-forrest.jpg"},
{id:"51", APIname:"labrador", commonName: "Labrador Retriver", dogPic: "https://images.dog.ceo/breeds/labrador/Luke.jpg"},
{id:"52", APIname:"labrador", commonName: "Labrador Retriver", dogPic: "https://images.dog.ceo/breeds/labrador/n02099712_7866.jpg"},
{id:"53", APIname:"maltese", commonName: "Maltese", dogPic: "https://images.dog.ceo/breeds/maltese/n02085936_5582.jpg"},
{id:"54", APIname:"maltese", commonName: "Maltese", dogPic: "https://images.dog.ceo/breeds/maltese/n02085936_9812.jpg"},
{id:"55", APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/2.jpg"},
{id:"56", APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/2.jpg"},
{id:"57", APIname:"mix", commonName: "Mix", dogPic: "https://images.dog.ceo/breeds/mix/luna.jpg"},
{id:"58", APIname:"mix", commonName: "Mix", dogPic: "https://images.dog.ceo/breeds/mix/Polo.jpg"},
{id:"59", APIname:"mountain/bernese", commonName: "Bernese Mountain", dogPic: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_3908.jpg"},
{id:"60", APIname:"mountain/bernese", commonName: "Bernese Mountain", dogPic: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_4061.jpg"},
{id:"61", APIname:"newfoundland", commonName: "Newfoundland", dogPic: "https://images.dog.ceo/breeds/newfoundland/n02111277_3653.jpg"},
{id:"62", APIname:"newfoundland", commonName: "Newfoundland", dogPic: "https://images.dog.ceo/breeds/newfoundland/n02111277_7225.jpg"},
{id:"63", APIname:"pinscher/miniature", commonName: "Miniature Pinscher", dogPic: "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_3823.jpg"},
{id:"64", APIname:"pinscher/miniature", commonName: "Miniature Pinscher", dogPic: "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_957.jpg"},
{id:"65", APIname:"pitbull", commonName: "Pitbull", dogPic: "https://images.dog.ceo/breeds/pitbull/20190710_143021.jpg"},
{id:"66", APIname:"pitbull", commonName: "Pitbull", dogPic: "https://images.dog.ceo/breeds/pitbull/20190801_154956.jpg"},
{id:"67", APIname:"pointer/german", commonName: "German Pointer", dogPic: "https://images.dog.ceo/breeds/pointer-german/n02100236_2974.jpg"},
{id:"68", APIname:"pointer/german", commonName: "German Pointer", dogPic: "https://images.dog.ceo/breeds/pointer-german/n02100236_5141.jpg"},
{id:"69", APIname:"pomeranian", commonName: "Pomeranian", dogPic: "https://images.dog.ceo/breeds/pomeranian/n02112018_6149.jpg"},
{id:"70", APIname:"pomeranian", commonName: "Pomeranian", dogPic: "https://images.dog.ceo/breeds/pomeranian/n02112018_725.jpg"},
{id:"71", APIname:"poodle/toy", commonName: "Toy Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-toy/n02113624_2308.jpg"},
{id:"72", APIname:"poodle/toy", commonName: "Toy Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-toy/n02113624_3624.jpg"},
{id:"73", APIname:"poodle/standard", commonName: "Standard Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-standard/n02113799_153.jpg"},
{id:"74", APIname:"poodle/standard", commonName: "Standard Poodle", dogPic: "https://images.dog.ceo/breeds/poodle-standard/n02113799_2466.jpg"},
{id:"75", APIname:"pug", commonName: "Pug", dogPic: "https://images.dog.ceo/breeds/pug/n02110958_11306.jpg"},
{id:"76", APIname:"pug", commonName: "Pug", dogPic: "https://images.dog.ceo/breeds/pug/n02110958_16082.jpg"},
{id:"77", APIname:"retriever/golden", commonName: "Golden Retriever", dogPic: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3494.jpg"},
{id:"78", APIname:"retriever/golden", commonName: "Golden Retriever", dogPic: "https://images.dog.ceo/breeds/retriever-golden/PXL_20220424_121025943.MP.jpg"},
{id:"79", APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/3.jpg"},
{id:"80", APIname:"mastiff/english", commonName: "English Mastiff", dogPic: "https://images.dog.ceo/breeds/mastiff-english/4.jpg"},
{id:"81", APIname:"samoyed", commonName: "Samoyed", dogPic: "https://images.dog.ceo/breeds/samoyed/n02111889_3960.jpg"},
{id:"82", APIname:"samoyed", commonName: "Samoyed", dogPic: "https://images.dog.ceo/breeds/samoyed/ruby.jpg"},
{id:"83", APIname:"setter/english", commonName: "English Setter", dogPic: "https://images.dog.ceo/breeds/setter-english/n02100735_4172.jpg"},
{id:"84", APIname:"setter/english", commonName: "English Setter", dogPic: "https://images.dog.ceo/breeds/setter-english/n02100735_6658.jpg"},
{id:"85", APIname:"setter/irish", commonName: "Irish Setter", dogPic: "https://images.dog.ceo/breeds/setter-irish/n02100877_5925.jpg"},
{id:"86", APIname:"setter/irish", commonName: "Irish Setter", dogPic: "https://images.dog.ceo/breeds/setter-irish/n02100877_8595.jpg"},
{id:"87", APIname:"sheepdog/english", commonName: "English Sheepdog", dogPic: "https://images.dog.ceo/breeds/sheepdog-english/n02105641_12610.jpg"},
{id:"88", APIname:"sheepdog/english", commonName: "English Sheepdog", dogPic: "https://images.dog.ceo/breeds/sheepdog-english/n02105641_4796.jpg"},
{id:"89", APIname:"shiba", commonName: "Shiba Inu", dogPic: "https://images.dog.ceo/breeds/shiba/kurosuke01.jpg"},
{id:"90", APIname:"shiba", commonName: "Shiba Inu", dogPic: "https://images.dog.ceo/breeds/shiba/shiba-1.jpg"},
{id:"91", APIname:"spaniel/cocker", commonName: "Cocker Spaniel", dogPic: "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_11443.jpg"},
{id:"92", APIname:"spaniel/cocker", commonName: "Cocker Spaniel", dogPic: "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_4782.jpg"},
{id:"93", APIname:"springer/english", commonName: "English Springer", dogPic: "https://images.dog.ceo/breeds/springer-english/n02102040_5604.jpg"},
{id:"94", APIname:"springer/english", commonName: "English Springer", dogPic: "https://images.dog.ceo/breeds/springer-english/n02102040_735.jpg"},
{id:"95", APIname:"terrier/american", commonName: "American Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-american/n02093428_111.jpg"},
{id:"96", APIname:"terrier/american", commonName: "American Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-american/n02093428_2049.jpg"},
{id:"97", APIname:"terrier/scottish", commonName: "Scotish Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-scottish/n02097298_8452.jpg"},
{id:"98", APIname:"terrier/scottish", commonName: "Scotish Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-scottish/n02097298_9499.jpg"},
{id:"99", APIname:"terrier/yorkshire", commonName: "Yorkshire Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2748.jpg"},
{id:"100", APIname:"terrier/yorkshire", commonName: "Yorkshire Terrier", dogPic: "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3704.jpg"},
{id:"101", APIname:"weimaraner", commonName: "Weimaraner", dogPic: "https://images.dog.ceo/breeds/weimaraner/n02092339_1331.jpg"},
{id:"102", APIname:"weimaraner", commonName: "Weimaraner", dogPic: "https://images.dog.ceo/breeds/weimaraner/n02092339_452.jpg"},
{id:"103", APIname:"whippet", commonName: "Whippet", dogPic: "https://images.dog.ceo/breeds/whippet/n02091134_15398.jpg"},
{id:"104", APIname:"whippet", commonName: "Whippet", dogPic: "https://images.dog.ceo/breeds/whippet/n02091134_3522.jpg"},
{id:"105", APIname:"wolfhound/irish", commonName: "Irish Wolfhound", dogPic: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_272.jpg"},
{id:"106", APIname:"wolfhound/irish", commonName: "Irish Wolfhound", dogPic: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_4006.jpg"}
]

const seedDogPics = () => DogPics.bulkCreate(DogsPicData);

module.exports = seedDogPics;
