INSERT INTO dogPics (APIname, commonName, dogPic) 
VALUES 
("appenzeller", "Appenzeller", "https://images.dog.ceo/breeds/appenzeller/n02107908_2340.jpg"),
("appenzeller", "Appenzeller", "https://images.dog.ceo/breeds/appenzeller/n02107908_3926.jpg"),
("chihuahua", "Chihuahua", "https://images.dog.ceo/breeds/chihuahua/n02085620_2517.jpg"),
("chihuahua", "Chihuahua", "https://images.dog.ceo/breeds/chihuahua/n02085620_275.jpg"),
("akita", "Akita", "https://images.dog.ceo/breeds/akita/An_Akita_Inu_resting.jpg"),
("akita", "Akita", "https://images.dog.ceo/breeds/akita/Japaneseakita.jpg"),
("basenji", "Basenji", "https://images.dog.ceo/breeds/basenji/n02110806_581.jpg"),
("basenji", "Basenji", "https://images.dog.ceo/breeds/basenji/n02110806_849.jpg"),
("chow", "Chow Chow", "https://images.dog.ceo/breeds/chow/n02112137_16665.jpg"),
("chow", "Chow Chow", "https://images.dog.ceo/breeds/chow/n02112137_16388.jpg"),
("labradoodle", "Labradoodle", "https://images.dog.ceo/breeds/labradoodle/labradoodle-forrest.jpg"),
("labradoodle", "Labradoodle", "https://images.dog.ceo/breeds/labradoodle/Cali.jpg"),
("australian/shepherd", "Australian Shepherd", "https://images.dog.ceo/breeds/australian-shepherd/forest.jpg"),
("australian/shepherd", "Australian Shepherd", "https://images.dog.ceo/breeds/australian-shepherd/sadie.jpg"),
("pomeranian", "Pomeranian", "https://images.dog.ceo/breeds/pomeranian/n02112018_725.jpg"),
("pomeranian", "Pomeranian", "https://images.dog.ceo/breeds/pomeranian/n02112018_6149.jpg"),
("dane/great", "Great Dane", "https://images.dog.ceo/breeds/dane-great/n02109047_1284.jpg"),
("dane/great", "Great Dane", "https://images.dog.ceo/breeds/dane-great/n02109047_1005.jpg"),
("springer/english", "English Springer", "https://images.dog.ceo/breeds/springer-english/n02102040_5604.jpg"),
("springer/english", "English Springer", "https://images.dog.ceo/breeds/springer-english/n02102040_735.jpg"),
("coonhound", "Bluetick Coonhound", "https://images.dog.ceo/breeds/coonhound/n02089078_3078.jpg"),
("coonhound", "Bluetick Coonhound", "https://images.dog.ceo/breeds/coonhound/n02089078_482.jpg"),
("bulldog/french", "French Bulldog", "https://images.dog.ceo/breeds/bulldog-french/n02108915_5596.jpg"),
("bulldog/french", "French Bulldog", "https://images.dog.ceo/breeds/bulldog-french/n02108915_618.jpg"),
("shiba", "Shiba Inu", "https://images.dog.ceo/breeds/shiba/kurosuke01.jpg"),
("shiba", "Shiba Inu", "https://images.dog.ceo/breeds/shiba/shiba-1.jpg"),
("setter/irish", "Irish Setter", "https://images.dog.ceo/breeds/setter-irish/n02100877_8595.jpg"),
("setter/irish", "Irish Setter", "https://images.dog.ceo/breeds/setter-irish/n02100877_5925.jpg"),
("mastiff/english", "English Mastiff", "https://images.dog.ceo/breeds/mastiff-english/4.jpg"),
("mastiff/english", "English Mastiff", "https://images.dog.ceo/breeds/mastiff-english/2.jpg"),
("labrador", "Labrador Retriver", "https://images.dog.ceo/breeds/labrador/Luke.jpg"),
("labrador", "Labrador Retriver", "https://images.dog.ceo/breeds/labrador/n02099712_7866.jpg"),
("bulldog/english", "English Bulldog", "https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg"),
("bulldog/english", "English Bulldog", "https://images.dog.ceo/breeds/bulldog-english/mami.jpg"),
("kelpie", "Kelpie", "https://images.dog.ceo/breeds/kelpie/n02105412_1530.jpg"),
("kelpie", "Kelpie", "https://images.dog.ceo/breeds/kelpie/n02105412_5702.jpg"),
("pitbull", "Pitbull", "https://images.dog.ceo/breeds/pitbull/20190710_143021.jpg"),
("pitbull", "Pitbull", "https://images.dog.ceo/breeds/pitbull/20190801_154956.jpg"),
("wolfhound/irish", "Irish Wolfhound", "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_272.jpg"),
("wolfhound/irish", "Irish Wolfhound", "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_4006.jpg"),
("pointer/german", "German Pointer", "https://images.dog.ceo/breeds/pointer-german/n02100236_5141.jpg"),
("pointer/german", "German Pointer", "https://images.dog.ceo/breeds/pointer-german/n02100236_2974.jpg"),
("hound/afghan", "Afghan Hound", "https://images.dog.ceo/breeds/hound-afghan/n02088094_1370.jpg"),
("hound/afghan", "Afghan Hound", "https://images.dog.ceo/breeds/hound-afghan/n02088094_10822.jpg"),
("terrier/american", "American Terrier", "https://images.dog.ceo/breeds/terrier-american/n02093428_2049.jpg"),
("terrier/american", "American Terrier", "https://images.dog.ceo/breeds/terrier-american/n02093428_111.jpg"),
("boxer", "Boxer", "https://images.dog.ceo/breeds/boxer/n02108089_2482.jpg"),
("boxer", "Boxer", "https://images.dog.ceo/breeds/boxer/n02108089_6008.jpg"),
("sheepdog/english", "English Sheepdog", "https://images.dog.ceo/breeds/sheepdog-english/n02105641_12610.jpg"),
("sheepdog/english", "English Sheepdog", "https://images.dog.ceo/breeds/sheepdog-english/n02105641_4796.jpg"),
("pug", "Pug", "https://images.dog.ceo/breeds/pug/n02110958_11306.jpg"),
("pug", "Pug", "https://images.dog.ceo/breeds/pug/n02110958_16082.jpg"),
("maltese", "Maltese", "https://images.dog.ceo/breeds/maltese/n02085936_9812.jpg"),
("maltese", "Maltese", "https://images.dog.ceo/breeds/maltese/n02085936_5582.jpg"),
("terrier/yorkshire", "Yorkshire Terrier", "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3704.jpg"),
("terrier/yorkshire", "Yorkshire Terrier", "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2748.jpg"),
("whippet", "Whippet", "https://images.dog.ceo/breeds/whippet/n02091134_15398.jpg"),
("whippet", "Whippet", "https://images.dog.ceo/breeds/whippet/n02091134_3522.jpg"),
("germanshepherd", "German Shepherd", "https://images.dog.ceo/breeds/germanshepherd/n02106662_2631.jpg"),
("germanshepherd", "German Shepherd", "https://images.dog.ceo/breeds/germanshepherd/n02106662_13368.jpg"),
("corgi/cardigan", "Corgi", "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_13484.jpg"),
("corgi/cardigan", "Corgi", "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11220.jpg"),
("dalmatian", "Dalmatian", "https://images.dog.ceo/breeds/dalmatian/cooper2.jpg"),
("dalmatian", "Dalmatian", "https://images.dog.ceo/breeds/dalmatian/cooper1.jpg"),
("pinscher/miniature", "Miniature Pinscher", "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_3823.jpg"),
("pinscher/miniature", "Miniature Pinscher", "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_957.jpg"),
("beagle", "Beagle", "https://images.dog.ceo/breeds/beagle/n02088364_11147.jpg"),
("beagle", "Beagle", "https://images.dog.ceo/breeds/beagle/n02088364_852.jpg"),
("poodle/toy", "Toy Poodle", "https://images.dog.ceo/breeds/poodle-toy/n02113624_3624.jpg"),
("poodle/toy", "Toy Poodle", "https://images.dog.ceo/breeds/poodle-toy/n02113624_2308.jpg"),
("setter/english", "English Setter", "https://images.dog.ceo/breeds/setter-english/n02100735_4172.jpg"),
("setter/english", "English Setter", "https://images.dog.ceo/breeds/setter-english/n02100735_6658.jpg"),
("spaniel/cocker", "Cocker Spaniel", "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_11443.jpg"),
("spaniel/cocker", "Cocker Spaniel", "https://images.dog.ceo/breeds/spaniel-cocker/n02102318_4782.jpg"),
("dachshund", "Dachshund", "https://images.dog.ceo/breeds/dachshund/daschund-1.jpg"),
("dachshund", "Dachshund", "https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg"),
("doberman", "Doberman", "https://images.dog.ceo/breeds/doberman/n02107142_10070.jpg"),
("doberman", "Doberman", "https://images.dog.ceo/breeds/doberman/n02107142_9621.jpg"),
("newfoundland", "Newfoundland", "https://images.dog.ceo/breeds/newfoundland/n02111277_3653.jpg"),
("newfoundland", "Newfoundland", "https://images.dog.ceo/breeds/newfoundland/n02111277_7225.jpg"),
("cattledog/australian", "Australian Cattledog", "https://images.dog.ceo/breeds/cattledog-australian/IMG_1042.jpg"),
("cattledog/australian", "Australian Cattledog", "https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg"),
("collie/border", "Border Collie", "https://images.dog.ceo/breeds/collie-border/n02106166_7804.jpg"),
("collie/border", "Border Collie", "https://images.dog.ceo/breeds/collie-border/niuniu.jpg");
("terrier/scottish", "Scotish Terrier", "https://images.dog.ceo/breeds/terrier-scottish/n02097298_9499.jpg"),
("terrier/scottish", "Scotish Terrier", "https://images.dog.ceo/breeds/terrier-scottish/n02097298_8452.jpg"),
("weimaraner", "Weimaraner", "https://images.dog.ceo/breeds/weimaraner/n02092339_452.jpg"),
("weimaraner", "Weimaraner", "https://images.dog.ceo/breeds/weimaraner/n02092339_1331.jpg"),
("hound/blood", "Blood Hound", "https://images.dog.ceo/breeds/hound-blood/n02088466_7046.jpg"),
("hound/blood", "Blood Hound", "https://images.dog.ceo/breeds/hound-blood/n02088466_6834.jpg"),
("mastiff/english", "English Mastiff", "https://images.dog.ceo/breeds/mastiff-english/2.jpg"),
("mastiff/english", "English Mastiff", "https://images.dog.ceo/breeds/mastiff-english/3.jpg"),
("husky", "Husky", "https://images.dog.ceo/breeds/husky/n02110185_6105.jpg"),
("husky", "Husky", "https://images.dog.ceo/breeds/husky/n02110185_3589.jpg"),
("mix", "Mix", "https://images.dog.ceo/breeds/mix/luna.jpg"),
("mix", "Mix", "https://images.dog.ceo/breeds/mix/Polo.jpg"),
("poodle/standard", "Standard Poodle", "https://images.dog.ceo/breeds/poodle-standard/n02113799_2466.jpg"),
("poodle/standard", "Standard Poodle", "https://images.dog.ceo/breeds/poodle-standard/n02113799_153.jpg"),
("retriever/golden", "Golden Retriever", "https://images.dog.ceo/breeds/retriever-golden/PXL_20220424_121025943.MP.jpg"),
("retriever/golden", "Golden Retriever", "https://images.dog.ceo/breeds/retriever-golden/n02099601_3494.jpg"),
("samoyed", "Samoyed", "https://images.dog.ceo/breeds/samoyed/ruby.jpg"),
("samoyed", "Samoyed", "https://images.dog.ceo/breeds/samoyed/n02111889_3960.jpg"),
("greyhound/italian", "Italian Greyhound", "https://images.dog.ceo/breeds/greyhound-italian/n02091032_652.jpg"),
("greyhound/italian", "Italian Greyhound", "https://images.dog.ceo/breeds/greyhound-italian/n02091032_9018.jpg"),
("mountain/bernese", "Bernese Mountain", "https://images.dog.ceo/breeds/mountain-bernese/n02107683_3908.jpg"),
("mountain/bernese", "Bernese Mountain", "https://images.dog.ceo/breeds/mountain-bernese/n02107683_4061.jpg"),