INSERT INTO dogs (id, name, age, gender, commonName, breed, size);
VALUES
    (1, "Lola", 4, "female", "Akita", "large"),
    (2, "Hades", 11, "male", "Akita", "large"),
    (3, "Crom", 7, "female", "Appenzeller", "large"),
    (4, "Stella", 15, "male", "Appenzeller", "large"),
    (5, "Rosie", 9, "female", "Australian Shepherd", "medium"),
    (6, "Newman", 9, "male", "Australian Shepherd", "medium"),
    (7, "Nikki", 1, "female", "Basenji", "small"),
    (8, "Luke", 6, "male", "Basenji", "small"),
    (9, "Tootsie", 14, "female", "Beagle", "small"),
    (10, "Gizmo", 7, "male", "Beagle", "small"),
    (11, "Olive", 8, "female", "Bluetick Coonhound", "large"),
    (12, "Brutus", 2, "male", "Bluetick Coonhound", "large"),
    (13, "Jade", 6, "female", "Boxer", "medium"),
    (14, "Ruger", 7, "male", "Boxer", "medium"),
    (15, "Gemini", 6, "female", "English Bulldog", "medium"),
    (16, "Walter", 12, "male", "English Bulldog", "medium"),
    (17, "Bella", 11, "female", "French Bulldog", "small"),
    (18, "Dyson", 3, "male", "French Bulldog", "small"),
    (19, "Kiddo", 14, "female", "Australian Cattledog", "medium"),
    (20, "Buster", 1, "male", "Australian Cattledog", "medium"),
    (21, "name", 5, "female", "Chihuahua", "small"),
    (22, "name", 13, "male", "Chihuahua", "small"),
    (23, "name", 14, "female", "Chow Chow", "medium"),
    (24, "name", 15, "male", "Chow Chow", "medium"),
    (25, "name", 12, "female", "Border Collie", "medium"),
    (26, "name", 5, "male", "Border Collie", "medium"),
    (27, "name", 10, "female", "Corgi", "medium"),
    (28, "name", 8, "male", "Corgi", "medium"),
    (29, "name", 7, "female", "Dachshund", "medium"),
    (30, "name", 6, "male", "Dachshund", "medium"),
    (31, "name", 15, "female", "Dalmatian", "large"),
    (32, "name", 11, "male", "Dalmatian", "large"),
    (33, "name", 12, "female", "Great Dane", "large"),
    (34, "Scout", 3, "male", "Great Dane", "large"),
    (35, "name", 13, "female", "Doberman", "large"),
    (36, "name", 7, "male", "Doberman", "large"),
    (37, "name", 13, "female", "German Shepherd", "large"),
    (38, "name", 5, "male", "German Shepherd", "large"),
    (39, "name", 8, "female", "Italian Greyhound", "small"),
    (40, "name", 8, "male", "Italian Greyhound", "small"),
    (41, "name", 2, "female", "Afghan Hound", "medium"),
    (42, "name", 12, "male", "Afghan Hound", "medium"),
    (43, "name", 5, "female", "Blood Hound", "large"),
    (44, "name", 15, "male", "Blood Hound", "large"),
    (45, "name", 7, "female", "Husky", "large"),
    (46, "name", 14, "male", "Husky", "large"),
    (47, "name", 9, "female", "Kelpie", "medium"),
    (48, "name", 15, "male", "Kelpie", "medium"),
    (49, "name", 12, "female", "Labradoodle", "medium"),
    (50, "name", 4, "male", "Labradoodle", "medium"),
    (51, "name", 2, "female", "Labrador Retriver", "large"),
    (52, "name", 7, "male", "Labrador Retriver", "large"),
    (53, "name", 4, "female", "Maltese", "small"),
    (54, "name", 5, "male", "Maltese", "small"),
    (55, "name", 14, "female", "English Mastiff", "large"),
    (56, "name", 15, "male", "English Mastiff", "large"),
    (57, "name", 10, "female", "Mix", "medium"),
    (58, "name", 8, "male", "Mix", "medium"),
    (59, "name", 12, "female", "Bernese Mountain", "large"),
    (60, "name", 3, "male", "Bernese Mountain", "large"),
    (61, "name", 3, "female", "Newfoundland", "large"),
    (62, "name", 4, "male", "Newfoundland", "large"),
    (63, "name", 2, "female", "Miniature Pinscher", "small"),
    (64, "name", 15, "male", "Miniature Pinscher", "small"),
    (65, "name", 6, "female", "Pitbull", "large"),
    (66, "name", 4, "male", "Pitbull", "large"),
    (67, "name", 10, "female", "German Pointer", "medium"),
    (68, "name", 3, "male", "German Pointer", "medium"),
    (69, "name", 9, "female", "Pomeranian", "small"),
    (70, "name", 4, "male", "Pomeranian", "small"),
    (71, "name", 2, "female", "Toy Poodle", "small"),
    (72, "name", 10, "male", "Toy Poodle", "small"),
    (73, "name", 7, "female", "Standard Poodle", "large"),
    (74, "name", 3, "male", "Standard Poodle", "large"),
    (75, "name", 12, "female", "Pug", "small"),
    (76, "name", 2, "male", "Pug", "small"),
    (77, "name", 7, "female", "Golden Retriever", "medium"),
    (78, "name", 10, "male", "Golden Retriever", "medium"),
    (79, "name", 11, "female", "Rottweiler", "large"),
    (80, "name", 12 "male", "Rottweiler", "large"),
    (81, "name", 8, "female", "Samoyed", "large"),
    (82, "name", 9, "male", "Samoyed", "large"),
    (83, "name", 1, "female", "English Setter", "medium"),
    (84, "name", 3, "male", "English Setter", "medium"),
    (85, "name", 4, "female", "Irish Setter", "medium"),
    (86, "name", 4, "male", "Irish Setter", "medium"),
    (87, "name", 11, "female", "English Sheepdog", "large"),
    (88, "name", 7, "male", "English Sheepdog", "large"),
    (89, "name", 4, "female", "Shiba Inu", "medium"),
    (90, "name", 9, "male", "Shiba Inu", "medium"),
    (91, "name", 1, "female", "Cocker Spaniel", "small"),
    (92, "name", 7, "male", "Cocker Spaniel", "small"),
    (93, "name", 7, "female", "English Springer", "medium"),
    (94, "name", 3, "male", "English Springer", "medium"),
    (95, "name", 8, "female", "American Terrier", "small"),
    (96, "name", 5, "male", "American Terrier", "small"),
    (97, "name", 3, "female", "Scottish Terrier", "small"),
    (98, "name", 10, "male", "Scotish Terrier", "small"),
    (99, "name", 3, "female", "Yorkshire Terrier", "small"),
    (100, "name", 7, "male", "Yorkshire Terrier", "small"),
    (101, "name", 13, "female", "Weimaraner", "large"),
    (102, "name", 6, "male", "Weimaraner", "large"),
    (103, "name", 7, "female", "Whippet", "medium"),
    (104, "name", 9, "male", "Whippet", "medium"),
    (105, "name", 3, "female", "Irish Wolfhound", "large"),
    (106, "name", 2, "male", "Irish Wolfhound", "large");