INSERT INTO goodWith (commonName, otherDogs, cats, kids);
VALUES
    ("Akita", "no", "no", "no"),
    ("Appenzeller", "yes", "yes", "yes"),
    ("Australian Shepherd", "yes", "yes", "yes"),
    ("Basenji", "yes", "yes", "yes"),
    ("Beagle", "yes", "yes", "yes"),
    ("Bluetick Coonhound",  "yes", "no", "yes"),
    ("Boxer", "yes", "yes", "yes"),
    ("English Bulldog", "no", "no", "no"),
    ("French Bulldog", "yes", "yes", "yes"),
    ("Australian Cattledog", "yes", "yes", "yes"),
    ("Chihuahua", "yes", "yes", "yes"),
    ("Chow Chow", "no", "no", "no"),
    ("Border Collie", "yes", "yes", "yes"),
    ("Corgi", "yes", "yes", "yes"),
    ("Dachshund", "yes", "yes", "yes"),
    ("Dalmatian", "yes", "no", "no"),
    ("Great Dane", "yes", "yes", "yes"),
    ("Doberman", "yes", "yes", "yes"),
    ("German Shepherd", "yes", "yes", "yes"),
    ("Italian Greyhound", "yes", "yes", "yes"),
    ("Afghan Hound", "yes", "no", "no"),
    ("Blood Hound", "yes,", "no", "yes"),
    ("Husky", "yes", "yes", "yes"),
    ("Kelpie", "yes", "yes", "yes"),
    ("Labradoodle", "yes", "yes", "yes"),
    ("Labrador Retriver", "yes", "yes", "yes"),
    ("English Mastiff", "yes", "yes", "yes"),
    ("Mix", "yes", "yes", "yes"),
    ("Bernese Mountain", "yes", "yes", "yes"),
    ("Newfoundland", "yes", "yes", "yes"),
    ("Miniature Pinscher", "yes", "no", "yes"),
    ("Pitbull", "no", "no", "no"),
    ("German Pointer", "yes", "no", "no"),
    ("Pomeranian", "yes", "yes", "yes"),
    ("Toy Poodle", "yes", "yes", "yes"),
    ("Standard Poodle", "yes", "yes", "yes"),
    ("Pug", "yes", "yes", "yes"),
    ("Golden Retriever", "yes", "yes", "yes"),
    ("Rottweiler", "yes", "yes", "yes"),
    ("Samoyed", "yes", "yes", "no"),
    ("English Setter", "yes", "yes", "yes"),
    ("Irish Setter", "yes", "yes", "yes"),
    ("English Sheepdog", "no", "yes", "yes"),
    ("Shiba Inu", "no", "no", "no"),
    ("Cocker Spaniel", "yes", "yes", "yes"),
    ("English Springer", "yes", "no", "yes"),
    ("American Terrier", "yes", "yes", "no"),
    ("Scottish Terrier", "yes", "yes", "no"),
    ("Yorkshire Terrier", "yes", "yes", "no"),
    ("Weimaraner", "yes", "yes", "yes"),
    ("Whippet", "yes", "yes", "yes"),
    ("Irish Wolfhound", "yes", "yes", "yes");